# Generated by Django 5.1.3 on 2024-12-26 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0003_alter_products_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=0, verbose_name='Stok')),
                ('session_key', models.CharField(blank=True, max_length=32, null=True)),
                ('created_timestap', models.DateTimeField(auto_now_add=True, verbose_name='Eklenen tarih')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.products', verbose_name='Ürün')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcılar')),
            ],
            options={
                'verbose_name': 'Sepet',
                'verbose_name_plural': 'Sepet',
                'db_table': 'cart',
            },
        ),
    ]
