# Generated by Django 5.1.3 on 2024-12-18 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_products_color_products_feature_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('id',), 'verbose_name': 'Ürün', 'verbose_name_plural': 'Ürünler'},
        ),
    ]
